### ISSUE TITLE
Recordar los datos del formulario en la sección Búsqueda Avanzada

### ISSUE THREAD

**Issue by endnch** [endnch/HispachanFiles#11]
Actualmente al utilizar la opción Búsqueda Avanzada, los datos del formulario se borren cada vez que se actualiza la pagina. Hay que agregar la funcionalidad para que se carguen los últimos datos buscados automáticamente.

**Comment by ghost** [comment]
Puedes asignarme esto.

**Comment by endnch** [comment]
@tootofu Asignado

**Comment by ghost** [comment]
Recuerda cerrar esto 👍
